name: Docker build and push image

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Get the last tag and generate a new tag
        id: version
        run: |
          latest=$(git tag | grep '^v[0-9]\+$' | sort -V | tail -n1)
          if [ -z "$latest" ]; then
            next=v1
          else
            num=${latest#v}
            next=v$((num + 1))
          fi
          echo "Última tag: $latest"
          echo "Nova tag: $next"
          git tag "$next"
          git push origin "$next"
          echo "tag=$next" >> $GITHUB_OUTPUT

      - name: Login on Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image on Dockerhub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./infra/docker/Dockerfile
          push: true
          tags: thullyodev/myapp-fastapi:${{ steps.version.outputs.tag }}